[project]
name = "reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbus-next>=0.2.3",
    "pydantic>=2.11.3",
    "pydantic-settings>=2.9.1",
    "result>=0.17.0",
    "sensors-py>=2.0",
]
